IF OBJECT_ID(N'[RM_EF_MIGRATIONS_HISTORY]') IS NULL
BEGIN
    CREATE TABLE [RM_EF_MIGRATIONS_HISTORY] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK_RM_EF_MIGRATIONS_HISTORY] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
GO

IF NOT EXISTS (
    SELECT * FROM [RM_EF_MIGRATIONS_HISTORY]
    WHERE [MigrationId] = N'20250426111954_INITIAL'
)
BEGIN
    CREATE TABLE [RM_ROOM_AVAILABILITY] (
        [ID] int NOT NULL IDENTITY,
        [TYPE] nvarchar(max) NULL,
        [STATUS] nvarchar(max) NULL,
        [IS_DELETED] bit NOT NULL DEFAULT CAST(0 AS bit),
        [CREATED_DATE_TIME] datetime2 NOT NULL,
        [CREATED_BY] uniqueidentifier NULL,
        [CREATED_BY_USERNAME] nvarchar(max) NULL,
        [MODIFIED_DATE_TIME] datetime2 NOT NULL,
        [MODIFIED_BY] uniqueidentifier NULL,
        [MODIFIED_BY_USERNAME] nvarchar(max) NULL,
        CONSTRAINT [PK_RM_ROOM_AVAILABILITY] PRIMARY KEY ([ID])
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [RM_EF_MIGRATIONS_HISTORY]
    WHERE [MigrationId] = N'20250426111954_INITIAL'
)
BEGIN
    CREATE TABLE [RM_ROOM] (
        [ID] int NOT NULL IDENTITY,
        [NUMBER] nvarchar(max) NULL,
        [TYPE] nvarchar(max) NULL,
        [AVAILABILITY_LINK_ID] int NULL,
        [IS_DELETED] bit NOT NULL DEFAULT CAST(0 AS bit),
        [CREATED_DATE_TIME] datetime2 NOT NULL,
        [CREATED_BY] uniqueidentifier NULL,
        [CREATED_BY_USERNAME] nvarchar(max) NULL,
        [MODIFIED_DATE_TIME] datetime2 NOT NULL,
        [MODIFIED_BY] uniqueidentifier NULL,
        [MODIFIED_BY_USERNAME] nvarchar(max) NULL,
        CONSTRAINT [PK_RM_ROOM] PRIMARY KEY ([ID]),
        CONSTRAINT [FK_RM_ROOM_RM_ROOM_AVAILABILITY_AVAILABILITY_LINK_ID] FOREIGN KEY ([AVAILABILITY_LINK_ID]) REFERENCES [RM_ROOM_AVAILABILITY] ([ID]) ON DELETE CASCADE
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [RM_EF_MIGRATIONS_HISTORY]
    WHERE [MigrationId] = N'20250426111954_INITIAL'
)
BEGIN
    CREATE INDEX [IX_RM_ROOM_AVAILABILITY_LINK_ID] ON [RM_ROOM] ([AVAILABILITY_LINK_ID]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [RM_EF_MIGRATIONS_HISTORY]
    WHERE [MigrationId] = N'20250426111954_INITIAL'
)
BEGIN
    INSERT INTO [RM_EF_MIGRATIONS_HISTORY] ([MigrationId], [ProductVersion])
    VALUES (N'20250426111954_INITIAL', N'8.0.8');
END;
GO

COMMIT;
GO

