// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomManager.Infrastructure;

#nullable disable

namespace RoomManager.Infrastructure.Migrations
{
    [DbContext(typeof(RoomManagerContext))]
    [Migration("20250425200221_INITIAL")]
    partial class INITIAL
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RoomManager.Domain.Aggregates.RoomAggregate.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CreatedByUsername")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CREATED_BY_USERNAME");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_DATE_TIME");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_DELETED");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MODIFIED_BY");

                    b.Property<string>("ModifiedByUsername")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MODIFIED_BY_USERNAME");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFIED_DATE_TIME");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NUMBER");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TYPE");

                    b.HasKey("Id");

                    b.ToTable("RM_ROOM", (string)null);
                });

            modelBuilder.Entity("RoomManager.Domain.Aggregates.RoomAggregate.RoomAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CreatedByUsername")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CREATED_BY_USERNAME");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_DATE_TIME");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_DELETED");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MODIFIED_BY");

                    b.Property<string>("ModifiedByUsername")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MODIFIED_BY_USERNAME");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFIED_DATE_TIME");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("ROOM_LINK_ID");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RM_ROOM_AVAILABILITY", (string)null);
                });

            modelBuilder.Entity("RoomManager.Domain.Aggregates.RoomAggregate.RoomAvailability", b =>
                {
                    b.HasOne("RoomManager.Domain.Aggregates.RoomAggregate.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.Navigation("Room");
                });
#pragma warning restore 612, 618
        }
    }
}
